[build]
  publish = "exampleSite/public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.88.1"
  TZ = "America/Toronto"
  GIT_LFS_ENABLED = "1"
  GIT_LFS_FETCH_INCLUDE = "*.jpg,*.png,*.jpeg,*.svg,*.gif,*.pdf,*.mp4,*.bmp,*.webp,*.ico"
  HUGO_MODULE_REPLACEMENTS = "github.com/danielfdickinson/hugo-debug-tables -> ../../../repo"

[context.production]
  command = "_scripts/hugo-build \"$URL\""

[context.deploy-preview]
  command = "_scripts/hugo-build \"$DEPLOY_PRIME_URL\""

[context.branch-deploy]
  command = "_scripts/hugo-build \"$DEPLOY_PRIME_URL\""

[dev]
  command = "_scripts/hugo-serve"
  targetPort = 1313
  framework = "#custom"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[[plugins]]
  package = "netlify-plugin-html-validate"

[[plugins]]
  package = "netlify-plugin-checklinks"

    [plugins.inputs]
      checkExternal = false
      skipPatterns = [ "<link rel=\"alternate\" type=\"application/rss+xml\"", "<meta http-equiv=\"refresh\" content=\"0; url=", "<meta property=\"og:url\" content=\"", "<meta property=\"og:image\" content=\"" ]

[[plugins]]
  package = "netlify-plugin-minify-html"

    [plugins.inputs.minifierOptions]
    collapseBooleanAttributes = true
    decodeEntities = true
    preserveLineBreaks = true
    removeAttributeQuotes = false
    removeComments = true
    removeEmptyAttributes = true
    removeOptionalTags = false
    removeRedundantAttributes = true
    removeScriptTypeAttributes = true
    removeTypeLinkTypeAttributes = true
    useShortDocType = false
